name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        id: cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          output: release.md

      - name: Set tag name
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=main" >> "$GITHUB_OUTPUT"
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.md
          tag_name: ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
