name: Release

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Generate release notes
        id: cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          output: release.md

      - name: Check release notes
        run: test -f release.md

      - name: Set tag name
        id: vars
        run: |
          git fetch --tags
          if git describe --tags --exact-match >/dev/null 2>&1; then
            TAG=$(git describe --tags --exact-match)
          else
            TAG=main
          fi
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.md
          tag_name: ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
